name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add release key
      run: echo ${{ secrets.RELEASE_KEY }} > keys/build_key.txt
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_full.txt
    - name: Build Linux App
      run: python -m PyInstaller wwrando.spec
    - name: Bundle Linux App
      run: python build.py
    - uses: actions/upload-artifact@v2
      with:
        name: wwrando-linux
        path: dist/release_archive/*

  macos:
    runs-on: macos-latest

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      MACOSX_DEPLOYMENT_TARGET: 10.9

    steps:
      - uses: actions/checkout@v2
      - name: Add release key
        run: echo ${{ secrets.RELEASE_KEY }} > keys/build_key.txt
      - name: Set up Miniconda with Python 3.8
        uses: goanpeca/setup-miniconda@v1
        with:
          architecture: x64
          python-version: '3.8'
          miniconda-version: latest
      - run: |
          conda create -qyf -n py38 python=3.8 wheel -c anaconda
          conda activate py38
        shell: bash -l {0}
      - name: Install dependencies
        run: |
          conda install pip
          python3 -m pip install -r requirements_full.txt
        shell: bash -l {0}
      - name: Build MacOS App
        run: python3 -m PyInstaller --onefile --windowed wwrando.spec
        shell: bash -l {0}
      - name: Bundle MacOS App
        run: python3 build.py
        shell: bash -l {0}
      - uses: actions/upload-artifact@v2
        with:
          name: wwrando-macos
          path: dist/release_archive/*

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Add release key
        run: echo ${{ secrets.RELEASE_KEY }} > keys/build_key.txt
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_full.txt
      - name: Build Windows App
        run: python -m PyInstaller wwrando.spec
      - name: Bundle Windows App
        run: python build.py
      - uses: actions/upload-artifact@v2
        with:
         name: wwrando-windows
         path: dist/release_archive/*
